import Head from "next/head";
import { useState } from "react";
import QrReader from "react-qr-reader";
import Image from "next/image";
import styles from "@/styles/attendence.module.css";
import Link from "next/link";
import NavBar from "../../Components/Navbar";
export default function LoginPage() {
  const [selected, setSelected] = useState("environment");
  const [startScan, setStartScan] = useState(false);
  const [loadingScan, setLoadingScan] = useState(false);
  const [data, setData] = useState("");

  const handleScan = async (scanData) => {
    setLoadingScan(true);
    console.log(`loaded data data`, scanData);
    if (scanData && scanData !== "") {
      console.log(`loaded >>>`, scanData);
      setData(scanData);
      setStartScan(false);
      setLoadingScan(false);
      // setPrecScan(scanData);
    }
  };
  const handleError = (err) => {
    console.error(err);
  };
  return (
    <>
      <Head>
        <title>Mark samarth's attendence</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <NavBar />
      <main className={styles.main}>
        <div className="App">
          <h1>Hello CodeSandbox</h1>
          <h2>
            Last Scan:
            {selected}
          </h2>

          <button
            onClick={() => {
              setStartScan(!startScan);
            }}
          >
            {startScan ? "Stop Scan" : "Start Scan"}
          </button>
          {startScan && (
            <>
              <select onChange={(e) => setSelected(e.target.value)}>
                <option value={"environment"}>Back Camera</option>
                <option value={"user"}>Front Camera</option>
              </select>
              <QrReader
                facingMode={selected}
                delay={1000}
                onError={handleError}
                onScan={handleScan}
                // chooseDeviceId={()=>selected}
                style={{ width: "300px" }}
              />
            </>
          )}
          {loadingScan && <p>Loading</p>}
          {data !== "" && <p>{data}</p>}
        </div>
      </main>
    </>
  );
}
