import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Dashboard.module.css";
import Link from "next/link";
import NavBar from "../../Components/Navbar";
export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Samarth's Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <NavBar />
      <main className={styles.main}>
        <div className={styles.Lcontainer}>
          <h2 className={styles.head}>Overall Attendance</h2>
          <h5 className={styles.subhead}>Semester 7</h5>
          <svg viewBox="0 0 36 36" className={styles.circularchart}>
            <path
              className={styles.circlebg}
              d="M18 2.0845
          a 15.9155 15.9155 0 0 1 0 31.831
          a 15.9155 15.9155 0 0 1 0 -31.831"
            />
            <path
              className={styles.circle}
              stroke-dasharray="90, 100"
              d="M18 2.0845
          a 15.9155 15.9155 0 0 1 0 31.831
          a 15.9155 15.9155 0 0 1 0 -31.831"
            />
            <text x="18" y="20.35" className={styles.percentage}>
              90%
            </text>
          </svg>
          <div className={styles.box}>
            <div className={styles.first}>
              <div className={styles.num}>28</div>
              <div className={styles.para}>Attended</div>
            </div>
            <div className={styles.first}>
              <div className={styles.num}>30</div>
              <div className={styles.para}>Total</div>
            </div>
            <div className={styles.first}>
              <div className={styles.num}>2</div>
              <div className={styles.para}>Leaves</div>
            </div>
          </div>
        </div>
        <div className={styles.Lcontainer}>
          <div className={styles.head}>Subject-wise Attendance</div>

          <div className={styles.card}>
            <a className={styles.card1} href="#">
              <p>Social Media Lecture</p>
              <div className={styles.per}>70%</div>
              <p className={styles.small}>
                Maked attendance for 20 Aug 23' || Attended Classes:25 || Total
                Classes: 28
              </p>
              <div className={styles.gocorner} href="#">
                <div className={styles.goarrow}>→</div>
              </div>
            </a>
          </div>

          <div className={styles.card}>
            <a id="red" className={styles.card1} href="#">
              <p>CS Fundamentals Lecture</p>
              <div className={styles.per}>40%</div>
              <p className={styles.small}>
                Missed attendance for 20 Aug 23' || Attended Classes:20 || Total
                Classes: 29
              </p>
              <div className={styles.gocorner} href="#">
                <div className={styles.goarrow}>→</div>
              </div>
            </a>
          </div>
          <div className={styles.card}>
            <a className={styles.card1} href="#">
              <p>Operating System Lecture</p>
              <div className={styles.per}>65%</div>
              <p className={styles.small}>
                Maked attendance for 20 Aug 23' || Attended Classes:29 || Total
                Classes: 35
              </p>
              <div className={styles.gocorner} href="#">
                <div className={styles.goarrow}>→</div>
              </div>
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
