import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.container1}>
          <h1 className={styles.head}>Know Your TurnOut</h1>
          <Image src="/Hand.png" width={100} height={200} />
          <p className={styles.para}>
            Check attendance. Mark attendance. Calculate missed classes.
          </p>
          <p className={styles.para}>All of it: In one place</p>
          <Link class={styles.btn} href="/LoginPage">
            Take Me In!
          </Link>
        </div>
        <div className={styles.container2}>
          <div className={styles.top}>
            <Image src="/1.png" height={130} width={130} />
            <Image src="/2.png" height={130} width={130} />
            <Image src="/3.png" height={130} width={130} />
            <Image src="/4.png" height={130} width={130} />
          </div>
          <div className={styles.top}>
            <Image src="/5.png" height={130} width={130} />
            <Image src="/6.png" height={130} width={130} />
            <Image src="/7.png" height={130} width={130} />
            <Image src="/8.png" height={130} width={130} />
          </div>
          <div className={styles.top}>
            <Image src="/9.png" height={130} width={130} />
            <Image src="/10.png" height={130} width={130} />
            <Image src="/11.png" height={130} width={130} />
            <Image src="/12.png" height={130} width={130} />
          </div>
        </div>
      </main>
    </>
  );
}
