import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Login.module.css";
import Link from "next/link";

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main className={styles.main}>
        <div className={styles.formdata}>
          <form class={styles.form}>
            <p className={styles.title}>Let's Get You Started</p>
            <p className={styles.message}>Tell us something about yourself. </p>
            <Image src="/Folder.png" height={100} width={100} />
            {/* <div className={styles.flex}>
              <label>
                <input
                  required=""
                  placeholder=""
                  type="text"
                  className={styles.input}
                />
                <span>Name</span>
              </label>
            </div> */}

            <label>
              <input
                required=""
                placeholder=""
                type="name"
                className={styles.input}
              />
              <span>Name</span>
            </label>
            <label>
              <input
                required=""
                placeholder=""
                type="email"
                className={styles.input}
              />
              <span>Register No.</span>
            </label>

            <label>
              <input
                required=""
                placeholder=""
                type="password"
                className={styles.input}
              />
              <span>Password</span>
            </label>
            <Link href="/Dashboard" className={styles.button}>
              <span>I'm Done</span>
            </Link>
            <p className={styles.signin}>
              Already have an acount ? <a href="/">Signin</a>{" "}
            </p>
          </form>
        </div>
      </main>
    </>
  );
}
